#! /bin/sh

INITFILE=$HOME/.emacs.d/dotemacs/misc/compile-init.el
COMPILE_PATH=$HOME/.emacs.d/dotemacs/conf

elisp_files=$(find -L $COMPILE_PATH -iname "*.el")
compiled_files=$(find -L $COMPILE_PATH -iname "*.elc")

EMACS_ARGS="
--quick
--load $INITFILE
--batch
--funcall batch-byte-compile $elisp_files
"

rm -f $compiled_files

nice -n 5 ionice -c 3 emacs $EMACS_ARGS 2>&1 | grep -E "^Debugger entered|Error"

number_of_elisp_files=$(find -L $COMPILE_PATH -iname "*.el" | wc -l)
number_of_compiled_files=$(find -L $COMPILE_PATH -iname "*.elc" | wc -l)

echo "Compiled" $number_of_compiled_files/$number_of_elisp_files "files"
